"""Create CUSTOMER_ORDERS_DEMO table and indexes in adb_phoenix.

This mirrors the DDL used in adb_sanjose so that DBMS_CLOUD.COPY_DATA
can load data into the same structure in adb_phoenix.

Prerequisites:
    pip install oracledb
"""

import getpass
import sys

try:
    import oracledb
except ImportError:
    print("python-oracledb is not installed. Install it with: pip install oracledb")
    sys.exit(1)

# Easy Connect Plus-style descriptor for adb_phoenix (with wallet directory)
ADB_PHX_DSN = (
    "(description=(retry_count=20)(retry_delay=3)"
    "(address=(protocol=tcps)(port=1522)"
    "(host=adb.us-phoenix-1.oraclecloud.com))"
    "(connect_data=(service_name=bk8uwrvkgqzvi2h_adbphx_high.adb.oraclecloud.com))"
    "(security=(ssl_server_dn_match=yes)"
    "(my_wallet_directory=C:\\Users\\Blake\\Downloads\\Wallet_ADBPHX)))"
)


CREATE_TABLE_SQL = """
CREATE TABLE customer_orders_demo (
    order_id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,

    customer_id           NUMBER         NOT NULL,
    customer_name         VARCHAR2(100)  NOT NULL,
    customer_email        VARCHAR2(255)  NOT NULL,

    order_status          VARCHAR2(30)   NOT NULL,
    order_channel         VARCHAR2(20),

    order_date            DATE           NOT NULL,
    order_ts              TIMESTAMP(6) WITH LOCAL TIME ZONE
                                      DEFAULT SYSTIMESTAMP NOT NULL,

    shipping_address      CLOB,
    shipping_city         VARCHAR2(100),
    shipping_state        VARCHAR2(50),
    shipping_postal       VARCHAR2(20),
    shipping_country      VARCHAR2(50),
    shipping_status       VARCHAR2(50),

    order_total           NUMBER(12,2)   NOT NULL,
    discount_percent      NUMBER(5,2),
    tax_amount            NUMBER(10,2),
    currency_code         CHAR(3)        DEFAULT 'USD' NOT NULL,

    payment_method        VARCHAR2(30),
    payment_auth_code     VARCHAR2(32),

    is_fraud_suspected    CHAR(1)        DEFAULT 'N' NOT NULL,

    metadata_json         CLOB,
    product_details_json  CLOB,
    customer_notes        CLOB,

    created_at            TIMESTAMP(6)   DEFAULT SYSTIMESTAMP,
    updated_at            TIMESTAMP(6),

    order_year            NUMBER GENERATED ALWAYS AS (EXTRACT(YEAR FROM order_date)) VIRTUAL,

    CONSTRAINT co_demo_pk
        PRIMARY KEY (order_id),

    CONSTRAINT co_demo_ck_fraud_flag
        CHECK (is_fraud_suspected IN ('Y','N')),

    CONSTRAINT co_demo_ck_status
        CHECK (order_status IN (
            'NEW', 'PENDING_PAYMENT', 'PAID', 'SHIPPED',
            'DELIVERED', 'CANCELLED', 'RETURNED'
        )),

    CONSTRAINT co_demo_ck_ship_status
        CHECK (shipping_status IN (
            'PENDING', 'PICKED', 'IN_TRANSIT', 'DELIVERED',
            'RETURNED', 'LOST'
        )),

    CONSTRAINT co_demo_ck_metadata_json
        CHECK (metadata_json IS JSON),

    CONSTRAINT co_demo_ck_product_json
        CHECK (product_details_json IS JSON)
)
PARTITION BY RANGE (order_date)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION co_demo_p_before_2024 VALUES LESS THAN (DATE '2024-01-01')
)
"""


CREATE_INDEX_SQLS = [
    # Orders by customer and date range
    """
    CREATE INDEX co_demo_ix_customer_date
        ON customer_orders_demo (customer_id, order_date)
    """,
    # Orders by status and date
    """
    CREATE INDEX co_demo_ix_status_date
        ON customer_orders_demo (order_status, order_date)
    """,
    # Case-insensitive lookup by email
    """
    CREATE INDEX co_demo_ix_lower_email
        ON customer_orders_demo (LOWER(customer_email))
    """,
    # Analytics by order_year
    """
    CREATE INDEX co_demo_ix_order_year
        ON customer_orders_demo (order_year)
    """,
]


def main() -> None:
    print("This script will create CUSTOMER_ORDERS_DEMO and its indexes in adb_phoenix.")

    password = getpass.getpass(
        "Enter password for ADMIN on adb_phoenix (adbphx_high): "
    )

    try:
        with oracledb.connect(user="ADMIN", password=password, dsn=ADB_PHX_DSN) as conn:
            with conn.cursor() as cur:
                print("\nCreating table CUSTOMER_ORDERS_DEMO (if not exists)...")
                try:
                    cur.execute(CREATE_TABLE_SQL)
                    print("Table created successfully.")
                except Exception as e:
                    print("Warning: error while creating table (it may already exist):")
                    print(e)

                print("\nCreating indexes (if not exist)...")
                for sql in CREATE_INDEX_SQLS:
                    try:
                        cur.execute(sql)
                    except Exception as e:
                        print("Warning while creating index (it may already exist):")
                        print(e)
                print("Index creation attempts finished.")

                conn.commit()

    except Exception as e:
        print("An error occurred while creating the table or indexes in adb_phoenix:")
        print(e)
        sys.exit(1)


if __name__ == "__main__":
    main()
