"""Create CUSTOMER_ORDERS_DEMO table and indexes in adb_sanjose.

- Connects to Autonomous Database in San Jose using Easy Connect Plus + wallet
- Prompts for ADMIN password via getpass (no echo)
- Executes the approved CREATE TABLE DDL
- Executes the CREATE INDEX statements
- Verifies creation via:
    SELECT table_name FROM user_tables WHERE table_name = 'CUSTOMER_ORDERS_DEMO';

Run this script BEFORE running generate_customer_orders_demo.py.

Prerequisites:
    pip install oracledb
"""

import getpass
import sys

try:
    import oracledb
except ImportError as exc:  # pragma: no cover - environment-specific
    print("python-oracledb is not installed.")
    print("Install it with: pip install oracledb")
    sys.exit(1)

# Easy Connect Plus-style descriptor for adb_sanjose (with wallet directory)
ADB_SJ_DSN = (
    "(description=(retry_count=20)(retry_delay=3)"
    "(address=(protocol=tcps)(port=1522)"
    "(host=adb.us-sanjose-1.oraclecloud.com))"
    "(connect_data=(service_name=fp7cb75hkszpygo_adbsj_high.adb.oraclecloud.com))"
    "(security=(ssl_server_dn_match=yes)"
    "(my_wallet_directory=C:\\Users\\Blake\\Downloads\\Wallet_ADBSJ)))"
)


CREATE_TABLE_SQL = """
CREATE TABLE customer_orders_demo (
    order_id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,

    customer_id           NUMBER         NOT NULL,
    customer_name         VARCHAR2(100)  NOT NULL,
    customer_email        VARCHAR2(255)  NOT NULL,

    order_status          VARCHAR2(30)   NOT NULL,
    order_channel         VARCHAR2(20),

    order_date            DATE           NOT NULL,
    order_ts              TIMESTAMP(6) WITH LOCAL TIME ZONE
                                      DEFAULT SYSTIMESTAMP NOT NULL,

    shipping_address      CLOB,
    shipping_city         VARCHAR2(100),
    shipping_state        VARCHAR2(50),
    shipping_postal       VARCHAR2(20),
    shipping_country      VARCHAR2(50),
    shipping_status       VARCHAR2(50),

    order_total           NUMBER(12,2)   NOT NULL,
    discount_percent      NUMBER(5,2),
    tax_amount            NUMBER(10,2),
    currency_code         CHAR(3)        DEFAULT 'USD' NOT NULL,

    payment_method        VARCHAR2(30),
    payment_auth_code     VARCHAR2(32),

    is_fraud_suspected    CHAR(1)        DEFAULT 'N' NOT NULL,

    metadata_json         CLOB,
    product_details_json  CLOB,
    customer_notes        CLOB,

    created_at            TIMESTAMP(6)   DEFAULT SYSTIMESTAMP,
    updated_at            TIMESTAMP(6),

    order_year            NUMBER GENERATED ALWAYS AS (EXTRACT(YEAR FROM order_date)) VIRTUAL,

    CONSTRAINT co_demo_pk
        PRIMARY KEY (order_id),

    CONSTRAINT co_demo_ck_fraud_flag
        CHECK (is_fraud_suspected IN ('Y','N')),

    CONSTRAINT co_demo_ck_status
        CHECK (order_status IN (
            'NEW', 'PENDING_PAYMENT', 'PAID', 'SHIPPED',
            'DELIVERED', 'CANCELLED', 'RETURNED'
        )),

    CONSTRAINT co_demo_ck_ship_status
        CHECK (shipping_status IN (
            'PENDING', 'PICKED', 'IN_TRANSIT', 'DELIVERED',
            'RETURNED', 'LOST'
        )),

    CONSTRAINT co_demo_ck_metadata_json
        CHECK (metadata_json IS JSON),

    CONSTRAINT co_demo_ck_product_json
        CHECK (product_details_json IS JSON)
)
PARTITION BY RANGE (order_date)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION co_demo_p_before_2024 VALUES LESS THAN (DATE '2024-01-01')
)
"""


CREATE_INDEX_SQLS = [
    # Orders by customer and date range
    """
    CREATE INDEX co_demo_ix_customer_date
        ON customer_orders_demo (customer_id, order_date)
    """,
    # Orders by status and date
    """
    CREATE INDEX co_demo_ix_status_date
        ON customer_orders_demo (order_status, order_date)
    """,
    # Case-insensitive lookup by email
    """
    CREATE INDEX co_demo_ix_lower_email
        ON customer_orders_demo (LOWER(customer_email))
    """,
    # Analytics by order_year
    """
    CREATE INDEX co_demo_ix_order_year
        ON customer_orders_demo (order_year)
    """,
]


def main() -> None:
    print("This script will create CUSTOMER_ORDERS_DEMO and its indexes in adb_sanjose.")

    password = getpass.getpass(
        "Enter password for ADMIN on adb_sanjose (adbsj_high): "
    )

    user = "ADMIN"

    try:
        with oracledb.connect(
            user=user,
            password=password,
            dsn=ADB_SJ_DSN,
        ) as conn:
            with conn.cursor() as cursor:
                print("\nCreating table CUSTOMER_ORDERS_DEMO...")
                cursor.execute(CREATE_TABLE_SQL)
                print("Table created successfully.")

                print("\nCreating indexes...")
                for sql in CREATE_INDEX_SQLS:
                    sql_clean = " ".join(sql.split())
                    cursor.execute(sql)
                print("Indexes created successfully.")

                # Verify table creation
                print("\nVerifying table existence...")
                cursor.execute(
                    "SELECT table_name FROM user_tables WHERE table_name = 'CUSTOMER_ORDERS_DEMO'"
                )
                row = cursor.fetchone()
                if row:
                    print(f"Found table: {row[0]}")
                else:
                    print("Table CUSTOMER_ORDERS_DEMO not found in USER_TABLES.")

                conn.commit()

    except Exception as e:  # pragma: no cover - manual diagnostics
        print("An error occurred while creating the table or indexes:")
        print(e)
        sys.exit(1)


if __name__ == "__main__":
    main()
